namespace ClaudePilot
{
    public static class ToolDefinitions
    {
        // Tool definitions as data
        private static readonly string[] toolDefs = new string[]
        {
            @"{""name"":""get_vessel_telemetry"",""description"":""Get full vessel state including altitude, velocity, attitude, and situation."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""get_orbit_info"",""description"":""Get orbital parameters: apoapsis, periapsis, period, inclination, eccentricity, etc."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""get_delta_v"",""description"":""Get per-stage delta-v information for the current vessel."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""get_resources"",""description"":""Get all resource amounts and capacities (fuel, oxidizer, electricity, etc)."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""get_available_bodies"",""description"":""Get list of celestial bodies in the solar system."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""set_target"",""description"":""Set a target celestial body or vessel by name."",""parameters"":{""type"":""object"",""properties"":{""name"":{""type"":""string"",""description"":""Name of the body or vessel to target""}},""required"":[""name""]}}",
            @"{""name"":""launch_to_orbit"",""description"":""Use MechJeb to launch to a circular orbit at the specified altitude and inclination."",""parameters"":{""type"":""object"",""properties"":{""altitude"":{""type"":""number"",""description"":""Target orbit altitude in meters (default 80000)""},""inclination"":{""type"":""number"",""description"":""Target orbit inclination in degrees (default 0)""}},""required"":[]}}",
            @"{""name"":""launch_to_orbit_wait"",""description"":""Use MechJeb to launch to orbit and WAIT until complete. Returns final telemetry when done. Use this for autonomous missions."",""parameters"":{""type"":""object"",""properties"":{""altitude"":{""type"":""number"",""description"":""Target orbit altitude in meters (default 80000)""},""inclination"":{""type"":""number"",""description"":""Target orbit inclination in degrees (default 0)""}},""required"":[]}}",
            @"{""name"":""plan_transfer"",""description"":""Plan a Hohmann transfer to a target body using MechJeb."",""parameters"":{""type"":""object"",""properties"":{""target_body"":{""type"":""string"",""description"":""Name of the target celestial body""}},""required"":[""target_body""]}}",
            @"{""name"":""circularize"",""description"":""Circularize the orbit at apoapsis or periapsis."",""parameters"":{""type"":""object"",""properties"":{""at_apoapsis"":{""type"":""boolean"",""description"":""Circularize at apoapsis (true) or periapsis (false). Default true.""}},""required"":[]}}",
            @"{""name"":""circularize_wait"",""description"":""Circularize orbit and WAIT until burn complete. Returns final orbit info."",""parameters"":{""type"":""object"",""properties"":{""at_apoapsis"":{""type"":""boolean"",""description"":""Circularize at apoapsis (true) or periapsis (false). Default true.""}},""required"":[]}}",
            @"{""name"":""execute_next_node"",""description"":""Execute the next maneuver node using MechJeb."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""execute_next_node_wait"",""description"":""Execute the next maneuver node using MechJeb and WAIT until complete. Returns telemetry when done."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""land"",""description"":""Land at a specific location or the nearest flat area using MechJeb."",""parameters"":{""type"":""object"",""properties"":{""latitude"":{""type"":""number"",""description"":""Target latitude (optional)""},""longitude"":{""type"":""number"",""description"":""Target longitude (optional)""}},""required"":[]}}",
            @"{""name"":""land_wait"",""description"":""Land using MechJeb and WAIT until touchdown. Returns final telemetry when on ground."",""parameters"":{""type"":""object"",""properties"":{""latitude"":{""type"":""number"",""description"":""Target latitude (optional)""},""longitude"":{""type"":""number"",""description"":""Target longitude (optional)""}},""required"":[]}}",
            @"{""name"":""start_rendezvous"",""description"":""Start MechJeb rendezvous autopilot with the current target."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""start_rendezvous_wait"",""description"":""Start MechJeb rendezvous autopilot and WAIT until complete."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""start_docking"",""description"":""Start MechJeb docking autopilot with the current target."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""start_docking_wait"",""description"":""Start MechJeb docking autopilot and WAIT until docked."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""set_time_warp"",""description"":""Set time warp rate by index (0=1x, 1=5x, 2=10x, 3=50x, 4=100x, 5=1000x, 6=10000x, 7=100000x)."",""parameters"":{""type"":""object"",""properties"":{""rate_index"":{""type"":""integer"",""description"":""Warp rate index from 0 to 7"",""minimum"":0,""maximum"":7}},""required"":[""rate_index""]}}",
            @"{""name"":""stop_time_warp"",""description"":""Stop time warp (set to 1x)."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""warp_to_next_node"",""description"":""Warp to a specified time before the next maneuver node."",""parameters"":{""type"":""object"",""properties"":{""lead_time"":{""type"":""number"",""description"":""Seconds before the node to stop warping (default 60)""}},""required"":[]}}",
            @"{""name"":""activate_stage"",""description"":""Activate the next stage on the vessel."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""set_sas_mode"",""description"":""Set the SAS autopilot mode."",""parameters"":{""type"":""object"",""properties"":{""mode"":{""type"":""string"",""description"":""SAS mode to set"",""enum"":[""stability"",""prograde"",""retrograde"",""normal"",""antinormal"",""radial_in"",""radial_out"",""target"",""anti_target"",""maneuver""]}},""required"":[""mode""]}}",
            @"{""name"":""toggle_action_group"",""description"":""Toggle a custom action group (1-10)."",""parameters"":{""type"":""object"",""properties"":{""group"":{""type"":""integer"",""description"":""Action group number (1-10)"",""minimum"":1,""maximum"":10}},""required"":[""group""]}}",
            @"{""name"":""wait_for_autopilot"",""description"":""Check if MechJeb autopilot is currently running and its status."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""list_craft_files"",""description"":""List available .craft files in VAB or SPH."",""parameters"":{""type"":""object"",""properties"":{""facility"":{""type"":""string"",""description"":""VAB or SPH"",""enum"":[""VAB"",""SPH""]}},""required"":[""facility""]}}",
            @"{""name"":""read_craft_file"",""description"":""Read the contents of a .craft file."",""parameters"":{""type"":""object"",""properties"":{""name"":{""type"":""string"",""description"":""Craft file name (without .craft extension)""},""facility"":{""type"":""string"",""description"":""VAB or SPH"",""enum"":[""VAB"",""SPH""]}},""required"":[""name"",""facility""]}}",
            @"{""name"":""analyze_craft"",""description"":""Analyze a craft file and return part count, mass, delta-v estimate, and structure."",""parameters"":{""type"":""object"",""properties"":{""name"":{""type"":""string"",""description"":""Craft file name (without .craft extension)""},""facility"":{""type"":""string"",""description"":""VAB or SPH"",""enum"":[""VAB"",""SPH""]}},""required"":[""name"",""facility""]}}",
            @"{""name"":""modify_craft_part"",""description"":""Modify a part in a craft file (swap, add, or remove)."",""parameters"":{""type"":""object"",""properties"":{""name"":{""type"":""string"",""description"":""Craft file name (without .craft extension)""},""facility"":{""type"":""string"",""description"":""VAB or SPH"",""enum"":[""VAB"",""SPH""]},""action"":{""type"":""string"",""description"":""Action to perform"",""enum"":[""swap"",""add"",""remove""]},""part_index"":{""type"":""integer"",""description"":""Index of the part to modify""},""new_part"":{""type"":""string"",""description"":""New part name (required for swap and add)""}},""required"":[""name"",""facility"",""action"",""part_index""]}}",
            @"{""name"":""get_delta_v_map"",""description"":""Get delta-v requirements for a route between two locations."",""parameters"":{""type"":""object"",""properties"":{""from"":{""type"":""string"",""description"":""Origin (e.g. Kerbin, Kerbin_LKO, Mun, Duna)""},""to"":{""type"":""string"",""description"":""Destination body name""}},""required"":[""from"",""to""]}}",
            @"{""name"":""get_full_delta_v_map"",""description"":""Get the complete delta-v map for all routes in the Kerbin system."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""suggest_mission"",""description"":""Get a suggested mission plan with steps and delta-v budget for a destination."",""parameters"":{""type"":""object"",""properties"":{""destination"":{""type"":""string"",""description"":""Target body (e.g. Mun, Duna, Eve)""},""round_trip"":{""type"":""boolean"",""description"":""Plan a return trip (default true)""}},""required"":[""destination""]}}",
            @"{""name"":""create_mission_plan"",""description"":""Create an active mission plan with a sequence of steps to execute."",""parameters"":{""type"":""object"",""properties"":{""name"":{""type"":""string"",""description"":""Mission name""},""destination"":{""type"":""string"",""description"":""Primary destination""},""steps_json"":{""type"":""string"",""description"":""JSON array of steps""}},""required"":[""name"",""destination"",""steps_json""]}}",
            @"{""name"":""get_mission_plan"",""description"":""Get the current active mission plan and status of all steps."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""update_mission_step"",""description"":""Update the status of a mission step."",""parameters"":{""type"":""object"",""properties"":{""step_index"":{""type"":""integer"",""description"":""Index of the step to update""},""status"":{""type"":""string"",""enum"":[""in_progress"",""completed"",""failed"",""skipped""]},""result"":{""type"":""string"",""description"":""Result or notes for this step (optional)""}},""required"":[""step_index"",""status""]}}",
            @"{""name"":""get_next_mission_step"",""description"":""Get the next pending step in the active mission plan."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""cancel_mission_plan"",""description"":""Cancel the active mission plan."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""go_to_vab"",""description"":""Switch to the Vehicle Assembly Building editor."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""go_to_sph"",""description"":""Switch to the Space Plane Hangar editor."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""go_to_tracking_station"",""description"":""Switch to the Tracking Station."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""go_to_space_center"",""description"":""Switch to the Space Center view."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""get_current_scene"",""description"":""Get info about the current game scene (Flight, Editor, SpaceCenter, etc)."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""load_craft_in_editor"",""description"":""Load a saved craft file in the current editor (must be in VAB/SPH)."",""parameters"":{""type"":""object"",""properties"":{""name"":{""type"":""string"",""description"":""Craft name (without .craft extension)""},""facility"":{""type"":""string"",""enum"":[""VAB"",""SPH""]}},""required"":[""name"",""facility""]}}",
            @"{""name"":""launch_vessel"",""description"":""Launch the currently loaded vessel from the editor."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""quick_launch"",""description"":""Load a saved craft and launch it directly (works from any scene)."",""parameters"":{""type"":""object"",""properties"":{""name"":{""type"":""string"",""description"":""Craft name (without .craft extension)""},""facility"":{""type"":""string"",""enum"":[""VAB"",""SPH""]}},""required"":[""name"",""facility""]}}",
            @"{""name"":""recover_vessel"",""description"":""Recover the active vessel (must be landed/splashed near KSC)."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""execute_mission_plan"",""description"":""Execute the active mission plan automatically. Runs each step in sequence using the appropriate tools. Stops on failure or when complete."",""parameters"":{""type"":""object"",""properties"":{""stop_on_failure"":{""type"":""boolean"",""description"":""Stop execution if a step fails (default true)""}},""required"":[]}}",
            @"{""name"":""create_maneuver_node"",""description"":""Create a maneuver node with specific delta-v components at a future time."",""parameters"":{""type"":""object"",""properties"":{""prograde"":{""type"":""number"",""description"":""Prograde delta-v in m/s""},""normal"":{""type"":""number"",""description"":""Normal delta-v in m/s (default 0)""},""radial"":{""type"":""number"",""description"":""Radial delta-v in m/s (default 0)""},""ut"":{""type"":""number"",""description"":""Universal time for the node (optional, defaults to soon)""}},""required"":[""prograde""]}}",
            @"{""name"":""delete_all_maneuver_nodes"",""description"":""Delete all maneuver nodes on the current vessel."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""auto_transfer"",""description"":""Automatically calculate and execute a transfer to another body. Creates the maneuver node at the optimal time. This is the easiest way to go to other planets/moons."",""parameters"":{""type"":""object"",""properties"":{""target_body"":{""type"":""string"",""description"":""Destination body name (e.g. Mun, Minmus, Duna, Eve)""},""wait_for_window"":{""type"":""boolean"",""description"":""Wait for optimal transfer window (default true)""},""execute"":{""type"":""boolean"",""description"":""Execute the burn automatically (default true)""}},""required"":[""target_body""]}}",
            @"{""name"":""calculate_transfer"",""description"":""Calculate the delta-v and timing needed for a transfer to another body. Returns the node parameters without creating it."",""parameters"":{""type"":""object"",""properties"":{""target_body"":{""type"":""string"",""description"":""Destination body name (e.g. Mun, Minmus, Duna)""}},""required"":[""target_body""]}}",
            @"{""name"":""land_at"",""description"":""Land at a named location on Kerbin. Use this instead of land for easier landings at KSC."",""parameters"":{""type"":""object"",""properties"":{""location"":{""type"":""string"",""description"":""Named landing location: KSC, VAB, SPH, runway, launchpad, island_runway""}},""required"":[""location""]}}",
            @"{""name"":""get_landing_locations"",""description"":""Get list of known landing locations with coordinates."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""plane_set_heading"",""description"":""Set target heading for plane autopilot (KramaxAutoPilot). Use for atmospheric flight."",""parameters"":{""type"":""object"",""properties"":{""heading"":{""type"":""number"",""description"":""Target heading in degrees (0-360)""}},""required"":[""heading""]}}",
            @"{""name"":""plane_set_altitude"",""description"":""Set target altitude for plane autopilot."",""parameters"":{""type"":""object"",""properties"":{""altitude"":{""type"":""number"",""description"":""Target altitude in meters""}},""required"":[""altitude""]}}",
            @"{""name"":""plane_set_speed"",""description"":""Set target speed for plane autopilot."",""parameters"":{""type"":""object"",""properties"":{""speed"":{""type"":""number"",""description"":""Target speed in m/s""}},""required"":[""speed""]}}",
            @"{""name"":""plane_cruise"",""description"":""Set cruise mode with heading, altitude and speed. Best for flying to destinations."",""parameters"":{""type"":""object"",""properties"":{""heading"":{""type"":""number"",""description"":""Target heading (0-360)""},""altitude"":{""type"":""number"",""description"":""Target altitude in meters""},""speed"":{""type"":""number"",""description"":""Target speed in m/s""}},""required"":[""heading"",""altitude"",""speed""]}}",
            @"{""name"":""plane_fly_to"",""description"":""Fly to coordinates with autopilot."",""parameters"":{""type"":""object"",""properties"":{""latitude"":{""type"":""number"",""description"":""Target latitude""},""longitude"":{""type"":""number"",""description"":""Target longitude""},""altitude"":{""type"":""number"",""description"":""Target altitude in meters""}},""required"":[""latitude"",""longitude""]}}",
            @"{""name"":""plane_auto_land"",""description"":""Enable autoland mode."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""plane_disengage"",""description"":""Turn off all plane autopilot modes."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""warp_to_apoapsis"",""description"":""Warp to a specified time before apoapsis. Use this to coast to apoapsis before circularizing."",""parameters"":{""type"":""object"",""properties"":{""lead_time"":{""type"":""number"",""description"":""Seconds before apoapsis to stop warping (default 30)""}},""required"":[]}}",
            @"{""name"":""warp_to_periapsis"",""description"":""Warp to a specified time before periapsis."",""parameters"":{""type"":""object"",""properties"":{""lead_time"":{""type"":""number"",""description"":""Seconds before periapsis to stop warping (default 30)""}},""required"":[]}}",
            @"{""name"":""warp_to_time"",""description"":""Warp to a specific universal time (UT). Use this to warp to transfer windows."",""parameters"":{""type"":""object"",""properties"":{""ut"":{""type"":""number"",""description"":""Universal time to warp to""}},""required"":[""ut""]}}",
            @"{""name"":""warp_to_soi_change"",""description"":""Warp to just before the next SOI transition (entering/leaving a body's sphere of influence). Use after setting up a transfer orbit."",""parameters"":{""type"":""object"",""properties"":{""lead_time"":{""type"":""number"",""description"":""Seconds before SOI change to stop warping (default 60)""}},""required"":[]}}",
            @"{""name"":""get_maneuver_node_info"",""description"":""Get detailed info about the next maneuver node including predicted orbit and encounters."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""get_available_parts"",""description"":""Browse parts the player has UNLOCKED (respects tech tree in career/science mode, shows all in sandbox). Filter by category, search, size, or mod. Paginated — 30 per page. Use this to find correct part names for craft design."",""parameters"":{""type"":""object"",""properties"":{""category"":{""type"":""string"",""description"":""Filter by part category"",""enum"":[""Pods"",""FuelTank"",""Engine"",""Control"",""Structural"",""Coupling"",""Aero"",""Electrical"",""Communication"",""Science"",""Utility"",""Thermal"",""Payload"",""Ground"",""Cargo"",""Robotics""]},""search"":{""type"":""string"",""description"":""Search by name, title, description, manufacturer, or tags (e.g. 'terrier', 'solar', '%.%.%')""},""size"":{""type"":""string"",""description"":""Filter by diameter class"",""enum"":[""0.625"",""1.25"",""1.875"",""2.5"",""3.75"",""5""]},""mod"":{""type"":""string"",""description"":""Filter by mod name (e.g. 'NearFuture', 'ReStock', 'Squad' for stock)""},""include_locked"":{""type"":""boolean"",""description"":""Include parts not yet unlocked in tech tree (default false)""},""page"":{""type"":""integer"",""description"":""Page number for results (30 per page, default 1)""}},""required"":[]}}",
            @"{""name"":""get_part_categories"",""description"":""List all part categories with count of unlocked parts in each. Respects tech tree."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""create_craft"",""description"":""Create a new craft file from a list of parts. Specify parts with their names, stages, and parent connections. The craft should be loaded in editor afterward to verify attachments."",""parameters"":{""type"":""object"",""properties"":{""name"":{""type"":""string"",""description"":""Name for the new craft""},""facility"":{""type"":""string"",""description"":""VAB or SPH"",""enum"":[""VAB"",""SPH""]},""parts_json"":{""type"":""string"",""description"":""JSON array of parts: [{name, stage, parent(index), y(optional)}]. Example: [{\\""name\\"":\\""mk1pod_v2\\""},{\\""name\\"":\\""FL-T400\\""},{\\""name\\"":\\""LV-T30\\""},{\\""name\\"":\\""solidBooster_v2\\""},{\\""name\\"":\\""mk16Parachute\\"",\\""parent\\"":\\""0\\""}}]""}},""required"":[""name"",""facility"",""parts_json""]}}",
            @"{""name"":""get_game_economy"",""description"":""Get current funds, science points, and reputation. Works in Career and Science modes."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""get_science_experiments"",""description"":""List all science experiments on the vessel, whether they have data, can be run, and estimated science value for the current situation/biome."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""run_experiment"",""description"":""Run a specific science experiment by index (from get_science_experiments)."",""parameters"":{""type"":""object"",""properties"":{""experiment_index"":{""type"":""integer"",""description"":""Index of the experiment to run (from get_science_experiments)""}},""required"":[""experiment_index""]}}",
            @"{""name"":""run_all_experiments"",""description"":""Run ALL available science experiments on the vessel at once. Skips experiments that are inoperable or already have data."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""collect_all_science"",""description"":""Collect all science data from experiments into the command pod/science container. Like EVA collect but automatic."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""transmit_all_science"",""description"":""Transmit all collected science data using antennas. Some experiments lose value when transmitted vs recovered."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""get_tech_tree"",""description"":""Get tech tree status: what's researched, what's available to research next (with costs and parts they unlock)."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""research_tech"",""description"":""Unlock a tech tree node by spending science points. Use get_tech_tree first to see available nodes and costs."",""parameters"":{""type"":""object"",""properties"":{""tech_id"":{""type"":""string"",""description"":""Tech node ID to research (from get_tech_tree)""}},""required"":[""tech_id""]}}",
            @"{""name"":""get_contracts"",""description"":""Get active and offered contracts with objectives, rewards (funds, science, reputation)."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""accept_contract"",""description"":""Accept an offered contract by index (from get_contracts offered list)."",""parameters"":{""type"":""object"",""properties"":{""contract_index"":{""type"":""integer"",""description"":""Index of the offered contract to accept""}},""required"":[""contract_index""]}}",
            @"{""name"":""get_crew_info"",""description"":""Get crew information for the active vessel: names, traits, levels, experience."",""parameters"":{""type"":""object"",""properties"":{},""required"":[]}}",
            @"{""name"":""go_eva"",""description"":""Send a crew member on EVA. They can collect science, plant flags, etc."",""parameters"":{""type"":""object"",""properties"":{""crew_index"":{""type"":""integer"",""description"":""Index of the crew member (from get_crew_info, default 0)""}},""required"":[]}}"
        };

        // OpenAI format tools
        public static string GetOpenAIToolsJson()
        {
            var sb = new System.Text.StringBuilder();
            sb.Append("[");
            for (int i = 0; i < toolDefs.Length; i++)
            {
                if (i > 0) sb.Append(",");
                sb.Append("{\"type\":\"function\",\"function\":");
                sb.Append(toolDefs[i]);
                sb.Append("}");
            }
            sb.Append("]");
            return sb.ToString();
        }

        // Legacy Anthropic format (for backward compatibility)
        public static string GetToolsJson()
        {
            var sb = new System.Text.StringBuilder();
            sb.Append("[");
            for (int i = 0; i < toolDefs.Length; i++)
            {
                if (i > 0) sb.Append(",");
                // Convert parameters to input_schema for Anthropic format
                string def = toolDefs[i];
                def = def.Replace(@"""parameters"":", @"""input_schema"":");
                sb.Append(def);
            }
            sb.Append("]");
            return sb.ToString();
        }
    }
}
